# Generated by Django 5.2 on 2026-10-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_username'),
        ('usuarios', '0003_usuario_username_required'),
    ]

    operations = [
    ]
