# Generated by Django 6.0.3 on 2026-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='subcategorias/'),
        ),
    ]
