# Generated by Django 6.0.3 on 2026-03-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], default='verde', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_actualizados', to='usuarios.usuario')),
                ('codigo_dos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.codigodos')),
                ('codigo_uno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.codigouno')),
                ('medida_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.medidaprincipal')),
                ('medida_secundaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.medidasecundaria')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.subcategoria')),
            ],
            options={
                'unique_together': {('subcategoria', 'medida_principal', 'medida_secundaria', 'codigo_uno', 'codigo_dos')},
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(max_length=255)),
                ('valor_nuevo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='usuarios.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='productos.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
