# Generated by Django 6.0.3 on 2026-03-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0002_codigo_unico_global'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo_uno', 'codigo_dos'), ('subcategoria', 'medida_principal', 'medida_secundaria')},
        ),
    ]
