# Generated by Django 6.0.3 on 2026-03-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_nombre_unico_por_caracteristicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['subcategoria__categoria', 'orden', 'id']},
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
